# Generated by Django 3.0.5 on 2020-08-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_module_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cost',
            field=models.CharField(blank=True, default='Free', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.CharField(blank=True, default=4.3, max_length=3),
        ),
    ]
