# Generated by Django 3.0.5 on 2020-08-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200809_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.CharField(blank=True, default=[8], max_length=3),
        ),
    ]
